# Generated by Django 3.0.3 on 2020-03-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Name of Article')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('article_test', models.TextField(verbose_name='Body of Article')),
                ('pub_date', models.DateTimeField(verbose_name='Date of Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name="Comment's Author")),
                ('comment_text', models.CharField(max_length=200, verbose_name="Comment's Body")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
